DROP SCHEMA IF EXISTS burger_db;

CREATE DATABASE IF NOT EXISTS burger_db;
USE burger_db;

CREATE TABLE IF NOT EXISTS tasks (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  burger_name VARCHAR(255) NOT NULL,
  devoured BOOLEAN 
);

